/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_simple_identifier = 1,
  anon_sym_NAMESPACE = 2,
  anon_sym_END_NAMESPACE = 3,
  anon_sym_TYPE = 4,
  anon_sym_END_TYPE = 5,
  anon_sym_STRUCT = 6,
  anon_sym_END_STRUCT = 7,
  anon_sym_SEMI = 8,
  anon_sym_COLON = 9,
  anon_sym_COLON_EQ = 10,
  anon_sym_RPAREN = 11,
  anon_sym_SInt = 12,
  anon_sym_Int = 13,
  anon_sym_DInt = 14,
  anon_sym_LInt = 15,
  anon_sym_USInt = 16,
  anon_sym_UInt = 17,
  anon_sym_UDInt = 18,
  anon_sym_ULInt = 19,
  anon_sym_Real = 20,
  anon_sym_LReal = 21,
  anon_sym_Date = 22,
  anon_sym_Time_Of_Day = 23,
  anon_sym_Tod = 24,
  anon_sym_Time = 25,
  anon_sym_Date_And_Time = 26,
  anon_sym_Dt = 27,
  anon_sym_Bool = 28,
  anon_sym_Byte = 29,
  anon_sym_Word = 30,
  anon_sym_DWord = 31,
  anon_sym_LWord = 32,
  anon_sym_String = 33,
  anon_sym_WString = 34,
  anon_sym_LBRACE = 35,
  anon_sym_RBRACE = 36,
  anon_sym_VERSION = 37,
  sym_string_literal = 38,
  anon_sym_POUND = 39,
  anon_sym_DOT = 40,
  sym__exponent = 41,
  sym__signed_integer = 42,
  sym__unsigned_integer = 43,
  sym_quoted_identifier = 44,
  sym_source_file = 45,
  sym__definitions = 46,
  sym_namespace = 47,
  sym_type_definition = 48,
  sym_struct_definition = 49,
  sym_fields = 50,
  sym_type = 51,
  sym_elementary_type = 52,
  sym_elementary_type_names = 53,
  sym_numeric_type_names = 54,
  sym_integer_type_names = 55,
  sym_signed_integer_type_names = 56,
  sym_unsigned_integer_type_names = 57,
  sym__real_type_names = 58,
  sym_date_type_names = 59,
  sym_bit_string_type_names = 60,
  sym_string_type_names = 61,
  sym_attributes = 62,
  sym_attribute_list = 63,
  sym_attribute = 64,
  sym_version = 65,
  sym_real_literal = 66,
  sym__real = 67,
  sym_identifier = 68,
  aux_sym_source_file_repeat1 = 69,
  aux_sym_struct_definition_repeat1 = 70,
  aux_sym_attribute_list_repeat1 = 71,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_simple_identifier] = "simple_identifier",
  [anon_sym_NAMESPACE] = "NAMESPACE",
  [anon_sym_END_NAMESPACE] = "END_NAMESPACE",
  [anon_sym_TYPE] = "TYPE",
  [anon_sym_END_TYPE] = "END_TYPE",
  [anon_sym_STRUCT] = "STRUCT",
  [anon_sym_END_STRUCT] = "END_STRUCT",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SInt] = "SInt",
  [anon_sym_Int] = "Int",
  [anon_sym_DInt] = "DInt",
  [anon_sym_LInt] = "LInt",
  [anon_sym_USInt] = "USInt",
  [anon_sym_UInt] = "UInt",
  [anon_sym_UDInt] = "UDInt",
  [anon_sym_ULInt] = "ULInt",
  [anon_sym_Real] = "Real",
  [anon_sym_LReal] = "LReal",
  [anon_sym_Date] = "Date",
  [anon_sym_Time_Of_Day] = "Time_Of_Day",
  [anon_sym_Tod] = "Tod",
  [anon_sym_Time] = "Time",
  [anon_sym_Date_And_Time] = "Date_And_Time",
  [anon_sym_Dt] = "Dt",
  [anon_sym_Bool] = "Bool",
  [anon_sym_Byte] = "Byte",
  [anon_sym_Word] = "Word",
  [anon_sym_DWord] = "DWord",
  [anon_sym_LWord] = "LWord",
  [anon_sym_String] = "String",
  [anon_sym_WString] = "WString",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_VERSION] = "VERSION",
  [sym_string_literal] = "string_literal",
  [anon_sym_POUND] = "#",
  [anon_sym_DOT] = ".",
  [sym__exponent] = "_exponent",
  [sym__signed_integer] = "_signed_integer",
  [sym__unsigned_integer] = "_unsigned_integer",
  [sym_quoted_identifier] = "quoted_identifier",
  [sym_source_file] = "source_file",
  [sym__definitions] = "_definitions",
  [sym_namespace] = "namespace",
  [sym_type_definition] = "type_definition",
  [sym_struct_definition] = "struct_definition",
  [sym_fields] = "fields",
  [sym_type] = "type",
  [sym_elementary_type] = "elementary_type",
  [sym_elementary_type_names] = "elementary_type_names",
  [sym_numeric_type_names] = "numeric_type_names",
  [sym_integer_type_names] = "integer_type_names",
  [sym_signed_integer_type_names] = "signed_integer_type_names",
  [sym_unsigned_integer_type_names] = "unsigned_integer_type_names",
  [sym__real_type_names] = "_real_type_names",
  [sym_date_type_names] = "date_type_names",
  [sym_bit_string_type_names] = "bit_string_type_names",
  [sym_string_type_names] = "string_type_names",
  [sym_attributes] = "attributes",
  [sym_attribute_list] = "attribute_list",
  [sym_attribute] = "attribute",
  [sym_version] = "version",
  [sym_real_literal] = "real_literal",
  [sym__real] = "_real",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_struct_definition_repeat1] = "struct_definition_repeat1",
  [aux_sym_attribute_list_repeat1] = "attribute_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_simple_identifier] = sym_simple_identifier,
  [anon_sym_NAMESPACE] = anon_sym_NAMESPACE,
  [anon_sym_END_NAMESPACE] = anon_sym_END_NAMESPACE,
  [anon_sym_TYPE] = anon_sym_TYPE,
  [anon_sym_END_TYPE] = anon_sym_END_TYPE,
  [anon_sym_STRUCT] = anon_sym_STRUCT,
  [anon_sym_END_STRUCT] = anon_sym_END_STRUCT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SInt] = anon_sym_SInt,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_DInt] = anon_sym_DInt,
  [anon_sym_LInt] = anon_sym_LInt,
  [anon_sym_USInt] = anon_sym_USInt,
  [anon_sym_UInt] = anon_sym_UInt,
  [anon_sym_UDInt] = anon_sym_UDInt,
  [anon_sym_ULInt] = anon_sym_ULInt,
  [anon_sym_Real] = anon_sym_Real,
  [anon_sym_LReal] = anon_sym_LReal,
  [anon_sym_Date] = anon_sym_Date,
  [anon_sym_Time_Of_Day] = anon_sym_Time_Of_Day,
  [anon_sym_Tod] = anon_sym_Tod,
  [anon_sym_Time] = anon_sym_Time,
  [anon_sym_Date_And_Time] = anon_sym_Date_And_Time,
  [anon_sym_Dt] = anon_sym_Dt,
  [anon_sym_Bool] = anon_sym_Bool,
  [anon_sym_Byte] = anon_sym_Byte,
  [anon_sym_Word] = anon_sym_Word,
  [anon_sym_DWord] = anon_sym_DWord,
  [anon_sym_LWord] = anon_sym_LWord,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_WString] = anon_sym_WString,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_VERSION] = anon_sym_VERSION,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym__exponent] = sym__exponent,
  [sym__signed_integer] = sym__signed_integer,
  [sym__unsigned_integer] = sym__unsigned_integer,
  [sym_quoted_identifier] = sym_quoted_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definitions] = sym__definitions,
  [sym_namespace] = sym_namespace,
  [sym_type_definition] = sym_type_definition,
  [sym_struct_definition] = sym_struct_definition,
  [sym_fields] = sym_fields,
  [sym_type] = sym_type,
  [sym_elementary_type] = sym_elementary_type,
  [sym_elementary_type_names] = sym_elementary_type_names,
  [sym_numeric_type_names] = sym_numeric_type_names,
  [sym_integer_type_names] = sym_integer_type_names,
  [sym_signed_integer_type_names] = sym_signed_integer_type_names,
  [sym_unsigned_integer_type_names] = sym_unsigned_integer_type_names,
  [sym__real_type_names] = sym__real_type_names,
  [sym_date_type_names] = sym_date_type_names,
  [sym_bit_string_type_names] = sym_bit_string_type_names,
  [sym_string_type_names] = sym_string_type_names,
  [sym_attributes] = sym_attributes,
  [sym_attribute_list] = sym_attribute_list,
  [sym_attribute] = sym_attribute,
  [sym_version] = sym_version,
  [sym_real_literal] = sym_real_literal,
  [sym__real] = sym__real,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_struct_definition_repeat1] = aux_sym_struct_definition_repeat1,
  [aux_sym_attribute_list_repeat1] = aux_sym_attribute_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_simple_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_NAMESPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_NAMESPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TYPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_TYPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STRUCT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_STRUCT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_USInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UDInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ULInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Real] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LReal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Time_Of_Day] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Tod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Time] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Date_And_Time] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Dt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Byte] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Word] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DWord] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LWord] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WString] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_VERSION] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__exponent] = {
    .visible = false,
    .named = true,
  },
  [sym__signed_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__unsigned_integer] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definitions] = {
    .visible = false,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_elementary_type] = {
    .visible = true,
    .named = true,
  },
  [sym_elementary_type_names] = {
    .visible = true,
    .named = true,
  },
  [sym_numeric_type_names] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_type_names] = {
    .visible = true,
    .named = true,
  },
  [sym_signed_integer_type_names] = {
    .visible = true,
    .named = true,
  },
  [sym_unsigned_integer_type_names] = {
    .visible = true,
    .named = true,
  },
  [sym__real_type_names] = {
    .visible = false,
    .named = true,
  },
  [sym_date_type_names] = {
    .visible = true,
    .named = true,
  },
  [sym_bit_string_type_names] = {
    .visible = true,
    .named = true,
  },
  [sym_string_type_names] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_list] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_real_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__real] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_value, 2},
  [2] =
    {field_name, 0},
    {field_value, 2},
  [4] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '"', 16,
        '#', 29,
        '\'', 2,
        ')', 25,
        '.', 30,
        ':', 23,
        ';', 21,
        'S', 38,
        '{', 26,
        '}', 27,
        '+', 13,
        '-', 13,
        'E', 41,
        'e', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(25);
      if (lookahead == ':') ADVANCE(22);
      if (lookahead == 'S') ADVANCE(9);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == ';') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'C') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'R') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'T') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'T') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'U') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(1);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == ':') ADVANCE(23);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STRUCT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_STRUCT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__exponent);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__exponent);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__signed_integer);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__unsigned_integer);
      if (lookahead == '_') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_quoted_identifier);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_simple_identifier);
      if (lookahead == 'C') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_simple_identifier);
      if (lookahead == 'R') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_simple_identifier);
      if (lookahead == 'T') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_simple_identifier);
      if (lookahead == 'T') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_simple_identifier);
      if (lookahead == 'U') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_simple_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_simple_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'B', 1,
        'D', 2,
        'E', 3,
        'I', 4,
        'L', 5,
        'N', 6,
        'R', 7,
        'S', 8,
        'T', 9,
        'U', 10,
        'V', 11,
        'W', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(13);
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'I') ADVANCE(15);
      if (lookahead == 'W') ADVANCE(16);
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'N') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'I') ADVANCE(21);
      if (lookahead == 'R') ADVANCE(22);
      if (lookahead == 'W') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'I') ADVANCE(26);
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'Y') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(29);
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'D') ADVANCE(31);
      if (lookahead == 'I') ADVANCE(32);
      if (lookahead == 'L') ADVANCE(33);
      if (lookahead == 'S') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'S') ADVANCE(36);
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_Dt);
      END_STATE();
    case 19:
      if (lookahead == 'D') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == 'M') ADVANCE(48);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == 'P') ADVANCE(52);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(53);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(54);
      END_STATE();
    case 31:
      if (lookahead == 'I') ADVANCE(55);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 33:
      if (lookahead == 'I') ADVANCE(57);
      END_STATE();
    case 34:
      if (lookahead == 'I') ADVANCE(58);
      END_STATE();
    case 35:
      if (lookahead == 'R') ADVANCE(59);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(61);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 43:
      if (lookahead == '_') ADVANCE(67);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_Int);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(69);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 48:
      if (lookahead == 'E') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(72);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 52:
      if (lookahead == 'E') ADVANCE(75);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_Tod);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 59:
      if (lookahead == 'S') ADVANCE(81);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'd') ADVANCE(83);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_Bool);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_Byte);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_DInt);
      END_STATE();
    case 65:
      if (lookahead == 'd') ADVANCE(84);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_Date);
      if (lookahead == '_') ADVANCE(85);
      END_STATE();
    case 67:
      if (lookahead == 'N') ADVANCE(86);
      if (lookahead == 'S') ADVANCE(87);
      if (lookahead == 'T') ADVANCE(88);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LInt);
      END_STATE();
    case 69:
      if (lookahead == 'l') ADVANCE(89);
      END_STATE();
    case 70:
      if (lookahead == 'd') ADVANCE(90);
      END_STATE();
    case 71:
      if (lookahead == 'S') ADVANCE(91);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_Real);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SInt);
      END_STATE();
    case 74:
      if (lookahead == 'n') ADVANCE(92);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_TYPE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_Time);
      if (lookahead == '_') ADVANCE(93);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_UInt);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(95);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 81:
      if (lookahead == 'I') ADVANCE(97);
      END_STATE();
    case 82:
      if (lookahead == 'i') ADVANCE(98);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_Word);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DWord);
      END_STATE();
    case 85:
      if (lookahead == 'A') ADVANCE(99);
      END_STATE();
    case 86:
      if (lookahead == 'A') ADVANCE(100);
      END_STATE();
    case 87:
      if (lookahead == 'T') ADVANCE(101);
      END_STATE();
    case 88:
      if (lookahead == 'Y') ADVANCE(102);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_LReal);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_LWord);
      END_STATE();
    case 91:
      if (lookahead == 'P') ADVANCE(103);
      END_STATE();
    case 92:
      if (lookahead == 'g') ADVANCE(104);
      END_STATE();
    case 93:
      if (lookahead == 'O') ADVANCE(105);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_UDInt);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_ULInt);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_USInt);
      END_STATE();
    case 97:
      if (lookahead == 'O') ADVANCE(106);
      END_STATE();
    case 98:
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 99:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 100:
      if (lookahead == 'M') ADVANCE(109);
      END_STATE();
    case 101:
      if (lookahead == 'R') ADVANCE(110);
      END_STATE();
    case 102:
      if (lookahead == 'P') ADVANCE(111);
      END_STATE();
    case 103:
      if (lookahead == 'A') ADVANCE(112);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 105:
      if (lookahead == 'f') ADVANCE(113);
      END_STATE();
    case 106:
      if (lookahead == 'N') ADVANCE(114);
      END_STATE();
    case 107:
      if (lookahead == 'g') ADVANCE(115);
      END_STATE();
    case 108:
      if (lookahead == 'd') ADVANCE(116);
      END_STATE();
    case 109:
      if (lookahead == 'E') ADVANCE(117);
      END_STATE();
    case 110:
      if (lookahead == 'U') ADVANCE(118);
      END_STATE();
    case 111:
      if (lookahead == 'E') ADVANCE(119);
      END_STATE();
    case 112:
      if (lookahead == 'C') ADVANCE(120);
      END_STATE();
    case 113:
      if (lookahead == '_') ADVANCE(121);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_VERSION);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_WString);
      END_STATE();
    case 116:
      if (lookahead == '_') ADVANCE(122);
      END_STATE();
    case 117:
      if (lookahead == 'S') ADVANCE(123);
      END_STATE();
    case 118:
      if (lookahead == 'C') ADVANCE(124);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_END_TYPE);
      END_STATE();
    case 120:
      if (lookahead == 'E') ADVANCE(125);
      END_STATE();
    case 121:
      if (lookahead == 'D') ADVANCE(126);
      END_STATE();
    case 122:
      if (lookahead == 'T') ADVANCE(127);
      END_STATE();
    case 123:
      if (lookahead == 'P') ADVANCE(128);
      END_STATE();
    case 124:
      if (lookahead == 'T') ADVANCE(129);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_NAMESPACE);
      END_STATE();
    case 126:
      if (lookahead == 'a') ADVANCE(130);
      END_STATE();
    case 127:
      if (lookahead == 'i') ADVANCE(131);
      END_STATE();
    case 128:
      if (lookahead == 'A') ADVANCE(132);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_END_STRUCT);
      END_STATE();
    case 130:
      if (lookahead == 'y') ADVANCE(133);
      END_STATE();
    case 131:
      if (lookahead == 'm') ADVANCE(134);
      END_STATE();
    case 132:
      if (lookahead == 'C') ADVANCE(135);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_Time_Of_Day);
      END_STATE();
    case 134:
      if (lookahead == 'e') ADVANCE(136);
      END_STATE();
    case 135:
      if (lookahead == 'E') ADVANCE(137);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_Date_And_Time);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_END_NAMESPACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 17},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 17},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 17},
  [33] = {.lex_state = 17},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 17},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 17},
  [49] = {.lex_state = 17},
  [50] = {.lex_state = 17},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 17},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 17},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_simple_identifier] = ACTIONS(1),
    [anon_sym_NAMESPACE] = ACTIONS(1),
    [anon_sym_END_NAMESPACE] = ACTIONS(1),
    [anon_sym_TYPE] = ACTIONS(1),
    [anon_sym_END_TYPE] = ACTIONS(1),
    [anon_sym_STRUCT] = ACTIONS(1),
    [anon_sym_END_STRUCT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SInt] = ACTIONS(1),
    [anon_sym_Int] = ACTIONS(1),
    [anon_sym_DInt] = ACTIONS(1),
    [anon_sym_LInt] = ACTIONS(1),
    [anon_sym_USInt] = ACTIONS(1),
    [anon_sym_UInt] = ACTIONS(1),
    [anon_sym_UDInt] = ACTIONS(1),
    [anon_sym_ULInt] = ACTIONS(1),
    [anon_sym_Real] = ACTIONS(1),
    [anon_sym_LReal] = ACTIONS(1),
    [anon_sym_Date] = ACTIONS(1),
    [anon_sym_Time_Of_Day] = ACTIONS(1),
    [anon_sym_Tod] = ACTIONS(1),
    [anon_sym_Time] = ACTIONS(1),
    [anon_sym_Date_And_Time] = ACTIONS(1),
    [anon_sym_Dt] = ACTIONS(1),
    [anon_sym_Bool] = ACTIONS(1),
    [anon_sym_Byte] = ACTIONS(1),
    [anon_sym_Word] = ACTIONS(1),
    [anon_sym_DWord] = ACTIONS(1),
    [anon_sym_LWord] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_WString] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_VERSION] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__exponent] = ACTIONS(1),
    [sym__signed_integer] = ACTIONS(1),
    [sym__unsigned_integer] = ACTIONS(1),
    [sym_quoted_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym__definitions] = STATE(5),
    [sym_namespace] = STATE(5),
    [sym_type_definition] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_NAMESPACE] = ACTIONS(5),
    [anon_sym_TYPE] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(23), 1,
      sym_quoted_identifier,
    STATE(39), 1,
      sym_elementary_type_names,
    STATE(54), 1,
      sym_elementary_type,
    STATE(55), 1,
      sym_type,
    ACTIONS(13), 2,
      anon_sym_Real,
      anon_sym_LReal,
    ACTIONS(15), 2,
      anon_sym_Date,
      anon_sym_Time,
    ACTIONS(21), 2,
      anon_sym_String,
      anon_sym_WString,
    STATE(41), 2,
      sym_integer_type_names,
      sym__real_type_names,
    STATE(42), 2,
      sym_signed_integer_type_names,
      sym_unsigned_integer_type_names,
    ACTIONS(9), 4,
      anon_sym_SInt,
      anon_sym_Int,
      anon_sym_DInt,
      anon_sym_LInt,
    ACTIONS(11), 4,
      anon_sym_USInt,
      anon_sym_UInt,
      anon_sym_UDInt,
      anon_sym_ULInt,
    ACTIONS(17), 4,
      anon_sym_Time_Of_Day,
      anon_sym_Tod,
      anon_sym_Date_And_Time,
      anon_sym_Dt,
    STATE(40), 4,
      sym_numeric_type_names,
      sym_date_type_names,
      sym_bit_string_type_names,
      sym_string_type_names,
    ACTIONS(19), 5,
      anon_sym_Bool,
      anon_sym_Byte,
      anon_sym_Word,
      anon_sym_DWord,
      anon_sym_LWord,
  [64] = 14,
    ACTIONS(23), 1,
      sym_quoted_identifier,
    STATE(39), 1,
      sym_elementary_type_names,
    STATE(54), 1,
      sym_elementary_type,
    STATE(65), 1,
      sym_type,
    ACTIONS(13), 2,
      anon_sym_Real,
      anon_sym_LReal,
    ACTIONS(15), 2,
      anon_sym_Date,
      anon_sym_Time,
    ACTIONS(21), 2,
      anon_sym_String,
      anon_sym_WString,
    STATE(41), 2,
      sym_integer_type_names,
      sym__real_type_names,
    STATE(42), 2,
      sym_signed_integer_type_names,
      sym_unsigned_integer_type_names,
    ACTIONS(9), 4,
      anon_sym_SInt,
      anon_sym_Int,
      anon_sym_DInt,
      anon_sym_LInt,
    ACTIONS(11), 4,
      anon_sym_USInt,
      anon_sym_UInt,
      anon_sym_UDInt,
      anon_sym_ULInt,
    ACTIONS(17), 4,
      anon_sym_Time_Of_Day,
      anon_sym_Tod,
      anon_sym_Date_And_Time,
      anon_sym_Dt,
    STATE(40), 4,
      sym_numeric_type_names,
      sym_date_type_names,
      sym_bit_string_type_names,
      sym_string_type_names,
    ACTIONS(19), 5,
      anon_sym_Bool,
      anon_sym_Byte,
      anon_sym_Word,
      anon_sym_DWord,
      anon_sym_LWord,
  [128] = 4,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_NAMESPACE,
    ACTIONS(30), 1,
      anon_sym_TYPE,
    STATE(4), 4,
      sym__definitions,
      sym_namespace,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [144] = 4,
    ACTIONS(5), 1,
      anon_sym_NAMESPACE,
    ACTIONS(7), 1,
      anon_sym_TYPE,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(4), 4,
      sym__definitions,
      sym_namespace,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [160] = 5,
    ACTIONS(35), 1,
      sym_simple_identifier,
    ACTIONS(37), 1,
      anon_sym_END_STRUCT,
    ACTIONS(39), 1,
      sym_quoted_identifier,
    STATE(21), 1,
      sym_identifier,
    STATE(9), 2,
      sym_fields,
      aux_sym_struct_definition_repeat1,
  [177] = 5,
    ACTIONS(43), 1,
      sym__signed_integer,
    STATE(27), 1,
      sym__real,
    STATE(53), 1,
      sym__real_type_names,
    STATE(57), 1,
      sym_real_literal,
    ACTIONS(41), 2,
      anon_sym_Real,
      anon_sym_LReal,
  [194] = 5,
    ACTIONS(35), 1,
      sym_simple_identifier,
    ACTIONS(39), 1,
      sym_quoted_identifier,
    ACTIONS(45), 1,
      anon_sym_END_STRUCT,
    STATE(21), 1,
      sym_identifier,
    STATE(6), 2,
      sym_fields,
      aux_sym_struct_definition_repeat1,
  [211] = 5,
    ACTIONS(47), 1,
      sym_simple_identifier,
    ACTIONS(50), 1,
      anon_sym_END_STRUCT,
    ACTIONS(52), 1,
      sym_quoted_identifier,
    STATE(21), 1,
      sym_identifier,
    STATE(9), 2,
      sym_fields,
      aux_sym_struct_definition_repeat1,
  [228] = 5,
    ACTIONS(43), 1,
      sym__signed_integer,
    STATE(27), 1,
      sym__real,
    STATE(53), 1,
      sym__real_type_names,
    STATE(66), 1,
      sym_real_literal,
    ACTIONS(41), 2,
      anon_sym_Real,
      anon_sym_LReal,
  [245] = 4,
    STATE(23), 1,
      sym_attribute,
    STATE(59), 1,
      sym_identifier,
    STATE(63), 1,
      sym_attribute_list,
    ACTIONS(39), 2,
      sym_quoted_identifier,
      sym_simple_identifier,
  [259] = 4,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      anon_sym_VERSION,
    STATE(33), 1,
      sym_attributes,
    STATE(34), 1,
      sym_version,
  [272] = 2,
    ACTIONS(59), 1,
      anon_sym_COLON,
    ACTIONS(61), 3,
      anon_sym_COLON_EQ,
      anon_sym_LBRACE,
      anon_sym_VERSION,
  [281] = 1,
    ACTIONS(63), 4,
      ts_builtin_sym_end,
      anon_sym_NAMESPACE,
      anon_sym_END_NAMESPACE,
      anon_sym_TYPE,
  [288] = 3,
    STATE(29), 1,
      sym_attribute,
    STATE(59), 1,
      sym_identifier,
    ACTIONS(39), 2,
      sym_quoted_identifier,
      sym_simple_identifier,
  [299] = 1,
    ACTIONS(65), 4,
      ts_builtin_sym_end,
      anon_sym_NAMESPACE,
      anon_sym_END_NAMESPACE,
      anon_sym_TYPE,
  [306] = 2,
    ACTIONS(69), 1,
      sym_quoted_identifier,
    ACTIONS(67), 2,
      anon_sym_END_STRUCT,
      sym_simple_identifier,
  [314] = 2,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(39), 2,
      sym_quoted_identifier,
      sym_simple_identifier,
  [322] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      aux_sym_attribute_list_repeat1,
  [332] = 3,
    ACTIONS(76), 1,
      anon_sym_SEMI,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      aux_sym_attribute_list_repeat1,
  [342] = 3,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 1,
      anon_sym_COLON,
    STATE(62), 1,
      sym_attributes,
  [352] = 2,
    ACTIONS(84), 1,
      sym__exponent,
    ACTIONS(82), 2,
      anon_sym_STRUCT,
      anon_sym_RPAREN,
  [360] = 3,
    ACTIONS(76), 1,
      anon_sym_SEMI,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym_attribute_list_repeat1,
  [370] = 1,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      anon_sym_NAMESPACE,
      anon_sym_TYPE,
  [376] = 2,
    ACTIONS(92), 1,
      sym_quoted_identifier,
    ACTIONS(90), 2,
      anon_sym_END_STRUCT,
      sym_simple_identifier,
  [384] = 1,
    ACTIONS(94), 2,
      anon_sym_COLON,
      anon_sym_VERSION,
  [389] = 1,
    ACTIONS(96), 2,
      anon_sym_STRUCT,
      anon_sym_RPAREN,
  [394] = 2,
    ACTIONS(98), 1,
      anon_sym_STRUCT,
    STATE(67), 1,
      sym_struct_definition,
  [401] = 1,
    ACTIONS(74), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [406] = 2,
    ACTIONS(7), 1,
      anon_sym_TYPE,
    STATE(49), 1,
      sym_type_definition,
  [413] = 1,
    ACTIONS(100), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [418] = 2,
    ACTIONS(43), 1,
      sym__signed_integer,
    STATE(45), 1,
      sym__real,
  [425] = 2,
    ACTIONS(57), 1,
      anon_sym_VERSION,
    STATE(28), 1,
      sym_version,
  [432] = 2,
    ACTIONS(98), 1,
      anon_sym_STRUCT,
    STATE(50), 1,
      sym_struct_definition,
  [439] = 1,
    ACTIONS(102), 2,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
  [444] = 1,
    ACTIONS(104), 2,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
  [449] = 1,
    ACTIONS(106), 2,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
  [454] = 1,
    ACTIONS(108), 2,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
  [459] = 2,
    ACTIONS(110), 1,
      anon_sym_SEMI,
    ACTIONS(112), 1,
      anon_sym_COLON_EQ,
  [466] = 1,
    ACTIONS(114), 2,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
  [471] = 1,
    ACTIONS(116), 2,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
  [476] = 1,
    ACTIONS(118), 2,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
  [481] = 1,
    ACTIONS(120), 2,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
  [486] = 1,
    ACTIONS(122), 2,
      anon_sym_STRUCT,
      anon_sym_RPAREN,
  [491] = 1,
    ACTIONS(124), 2,
      anon_sym_STRUCT,
      anon_sym_RPAREN,
  [496] = 1,
    ACTIONS(126), 1,
      anon_sym_END_TYPE,
  [500] = 1,
    ACTIONS(128), 1,
      anon_sym_SEMI,
  [504] = 1,
    ACTIONS(130), 1,
      sym_simple_identifier,
  [508] = 1,
    ACTIONS(132), 1,
      anon_sym_END_NAMESPACE,
  [512] = 1,
    ACTIONS(134), 1,
      anon_sym_END_TYPE,
  [516] = 1,
    ACTIONS(136), 1,
      sym_string_literal,
  [520] = 1,
    ACTIONS(138), 1,
      anon_sym_DOT,
  [524] = 1,
    ACTIONS(140), 1,
      anon_sym_POUND,
  [528] = 1,
    ACTIONS(142), 1,
      anon_sym_SEMI,
  [532] = 1,
    ACTIONS(144), 1,
      anon_sym_SEMI,
  [536] = 1,
    ACTIONS(146), 1,
      sym__unsigned_integer,
  [540] = 1,
    ACTIONS(148), 1,
      anon_sym_STRUCT,
  [544] = 1,
    ACTIONS(150), 1,
      anon_sym_COLON,
  [548] = 1,
    ACTIONS(152), 1,
      anon_sym_COLON_EQ,
  [552] = 1,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
  [556] = 1,
    ACTIONS(156), 1,
      anon_sym_END_TYPE,
  [560] = 1,
    ACTIONS(158), 1,
      anon_sym_COLON,
  [564] = 1,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
  [568] = 1,
    ACTIONS(162), 1,
      anon_sym_SEMI,
  [572] = 1,
    ACTIONS(164), 1,
      anon_sym_SEMI,
  [576] = 1,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
  [580] = 1,
    ACTIONS(168), 1,
      anon_sym_END_TYPE,
  [584] = 1,
    ACTIONS(170), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 64,
  [SMALL_STATE(4)] = 128,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 160,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 194,
  [SMALL_STATE(9)] = 211,
  [SMALL_STATE(10)] = 228,
  [SMALL_STATE(11)] = 245,
  [SMALL_STATE(12)] = 259,
  [SMALL_STATE(13)] = 272,
  [SMALL_STATE(14)] = 281,
  [SMALL_STATE(15)] = 288,
  [SMALL_STATE(16)] = 299,
  [SMALL_STATE(17)] = 306,
  [SMALL_STATE(18)] = 314,
  [SMALL_STATE(19)] = 322,
  [SMALL_STATE(20)] = 332,
  [SMALL_STATE(21)] = 342,
  [SMALL_STATE(22)] = 352,
  [SMALL_STATE(23)] = 360,
  [SMALL_STATE(24)] = 370,
  [SMALL_STATE(25)] = 376,
  [SMALL_STATE(26)] = 384,
  [SMALL_STATE(27)] = 389,
  [SMALL_STATE(28)] = 394,
  [SMALL_STATE(29)] = 401,
  [SMALL_STATE(30)] = 406,
  [SMALL_STATE(31)] = 413,
  [SMALL_STATE(32)] = 418,
  [SMALL_STATE(33)] = 425,
  [SMALL_STATE(34)] = 432,
  [SMALL_STATE(35)] = 439,
  [SMALL_STATE(36)] = 444,
  [SMALL_STATE(37)] = 449,
  [SMALL_STATE(38)] = 454,
  [SMALL_STATE(39)] = 459,
  [SMALL_STATE(40)] = 466,
  [SMALL_STATE(41)] = 471,
  [SMALL_STATE(42)] = 476,
  [SMALL_STATE(43)] = 481,
  [SMALL_STATE(44)] = 486,
  [SMALL_STATE(45)] = 491,
  [SMALL_STATE(46)] = 496,
  [SMALL_STATE(47)] = 500,
  [SMALL_STATE(48)] = 504,
  [SMALL_STATE(49)] = 508,
  [SMALL_STATE(50)] = 512,
  [SMALL_STATE(51)] = 516,
  [SMALL_STATE(52)] = 520,
  [SMALL_STATE(53)] = 524,
  [SMALL_STATE(54)] = 528,
  [SMALL_STATE(55)] = 532,
  [SMALL_STATE(56)] = 536,
  [SMALL_STATE(57)] = 540,
  [SMALL_STATE(58)] = 544,
  [SMALL_STATE(59)] = 548,
  [SMALL_STATE(60)] = 552,
  [SMALL_STATE(61)] = 556,
  [SMALL_STATE(62)] = 560,
  [SMALL_STATE(63)] = 564,
  [SMALL_STATE(64)] = 568,
  [SMALL_STATE(65)] = 572,
  [SMALL_STATE(66)] = 576,
  [SMALL_STATE(67)] = 580,
  [SMALL_STATE(68)] = 584,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_struct_definition_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 5, 0, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 6, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 4, 0, 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 4, 0, 4),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_list_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_list_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_list, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__real, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_list, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 4, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 5, 0, 4),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 5, 0, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_real_literal, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsigned_integer_type_names, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date_type_names, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bit_string_type_names, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_type_names, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elementary_type, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elementary_type_names, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numeric_type_names, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_type_names, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signed_integer_type_names, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__real, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_real_literal, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version, 3, 0, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [154] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elementary_type, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_scl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_simple_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "scl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
